### ISSUE TITLE
Can't scroll till snapping is done animating

### ISSUE THREAD

**Issue by Riyad95** [MSVCode/scroll_snap_list#3] opened 2020-04-14 05:52 UTC
hey!
great plugin and a huge time saver, absolutely loving it! thank you!
having a minor issue though, suppose i have a horizontal list with 100 items and i want to keep scrolling right, I swipe my finger and it scrolls like 20 of them, all good so far.. when I try to continue swiping right, if i do it before the list is done snapping then my swipe is not registered. I have to wait till it's done to be able to input my swipes.
Decreasing the duration makes it faster which:
1- doesn't really fix it and stays the same, i just have ti wait a bit less
2- makes the animation look bad

Is there a way to allow it to continue registering swipes? like allow my swipe to interrupt the snapping animation and continue the scrolling to the right even if the snapping animation is not done?
thank you!

**Comment by MSVCode** [comment] 2020-04-25 10:56
Thankyou @Riyad95 for your input!

This is unintended behavior caused by Flutter, it should be fixed now in version `0.3.1`

**Closed by MSVCode** 2020-04-25 10:56 UTC
